[package]
name = "probe_plotter"
version = "0.1.0"
edition = "2021"
authors = ["Samuel James"]

[dependencies]
clap = { version = "4.1.13", features = ["derive"] }
ron = "0.8.0"
serde = { version = "1", features = ["derive"] }
itertools = "0.10"
